
DROP TABLE IF EXISTS livro_autor;
DROP TABLE IF EXISTS autor;
DROP TABLE IF EXISTS livro;
DROP TABLE IF EXISTS usuario;


CREATE TABLE autora (
  id INTEGER NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) DEFAULT NULL,
  nome VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE livro (
  id INTEGER NOT NULL AUTO_INCREMENT,
  dataLancamento DATE DEFAULT NULL,
  isbn VARCHAR(255) DEFAULT NULL,
  preco double NOT NULL,
  titulo VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE livro_autor (
  livro_id INTEGER NOT NULL,
  autores_id INTEGER NOT NULL,
  PRIMARY KEY (livro_id, autores_id)
);

CREATE TABLE usuario (
  id INTEGER NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) DEFAULT NULL,
  senha VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE livro_autor ADD CONSTRAINT FK9590997AD70C7E4A FOREIGN KEY (autores_id) REFERENCES autor (id);
ALTER TABLE livro_autor ADD CONSTRAINT FK9590997AFA17418 FOREIGN KEY (livro_id) REFERENCES livro (id);
